version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: 6G

volumes:
  postgresql_data:
    driver: local
